{% set version = "1.4-1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mvtnorm
  version: "{{ version|replace("-", "_") }}"

source:
  url:
    - {{ cran_mirror }}/src/contrib/mvtnorm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mvtnorm/mvtnorm_{{ version }}.tar.gz
  sha256: cda87fb2bbf99e0bed40f9ea7bdaca647fba42845f12cc54bed8f3892e07c236

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
  host:
    - r-base
    - libblas
    - liblapack
  run:
    - r-base

test:
  commands:
    - $R -e "library('mvtnorm')"           # [not win]
    - "\"%R%\" -e \"library('mvtnorm')\""  # [win]

about:
  home: https://codeberg.org/thothorn/mvtnorm
  license: GPL-2.0-only
  summary: Computes multivariate normal and t probabilities, quantiles, random deviates, and densities. Log-likelihoods for multivariate Gaussian models and Gaussian copulae parameterised by Cholesky factors of covariance or precision matrices are implemented for interval-censored and exact data, or a mix thereof. 
    Score functions for these log-likelihoods are available. A class representing multiple lower triangular matrices and corresponding methods are part of this package.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
