{% set version = "1.2-3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mvtnorm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mvtnorm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mvtnorm/mvtnorm_{{ version }}.tar.gz
  sha256: 2adadc5df5e5303d51c9b0c1881930f51ff84bfb9b1a9754354e012f982bc6c7

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
  host:
    - r-base
    - libblas
    - liblapack
  run:
    - r-base
    - {{ native }}gcc-libs             # [win]

test:
  commands:
    - $R -e "library('mvtnorm')"           # [not win]
    - "\"%R%\" -e \"library('mvtnorm')\""  # [win]

about:
  home: http://mvtnorm.R-forge.R-project.org
  license: GPL-2.0-only
  summary: Computes multivariate normal and t probabilities, quantiles, random deviates and densities.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
